package com.qbwc.mytest.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ADVERTISE".
 */
public class Advertise extends BaseBean{

    private Long id;
    /** Not-null value. */
    private String title;
    private String subtitle;
    private String img_uri;
    private String click_uri;

    public Advertise() {
    }

    public Advertise(Long id) {
        this.id = id;
    }

    public Advertise(Long id, String title, String subtitle, String img_uri, String click_uri) {
        this.id = id;
        this.title = title;
        this.subtitle = subtitle;
        this.img_uri = img_uri;
        this.click_uri = click_uri;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getSubtitle() {
        return subtitle;
    }

    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    public String getImg_uri() {
        return img_uri;
    }

    public void setImg_uri(String img_uri) {
        this.img_uri = img_uri;
    }

    public String getClick_uri() {
        return click_uri;
    }

    public void setClick_uri(String click_uri) {
        this.click_uri = click_uri;
    }

}
