package com.qbwc.mytest.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.qbwc.mytest.entity.Advertise;

import com.qbwc.mytest.dao.AdvertiseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig advertiseDaoConfig;

    private final AdvertiseDao advertiseDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        advertiseDaoConfig = daoConfigMap.get(AdvertiseDao.class).clone();
        advertiseDaoConfig.initIdentityScope(type);

        advertiseDao = new AdvertiseDao(advertiseDaoConfig, this);

        registerDao(Advertise.class, advertiseDao);
    }
    
    public void clear() {
        advertiseDaoConfig.getIdentityScope().clear();
    }

    public AdvertiseDao getAdvertiseDao() {
        return advertiseDao;
    }

}
